app_name: Epic Network
app_subtitle: Earn Epic Token
app_download: https://mineepic.com/Epic.apk
app_github: https://apps.apple.com/us/app/epic-mining-network/id1661774148?uo=2
app_id: 1661774148
email: support@mineepic.com
app_icon: /assets/icon.png
favicon: /assets/icon.png

made_by: // Made by [Miká Kruschel](https://kruschel.dev)

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |

 EPIC is fairly distributed,
 eco-friendly and consumes minimal battery power.
 EPIC is fair and valuable to everyone.
    
####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
